Lab1
Regina-Kapralova/C_Sharp pull request #1
Opened 2022-10-11 12:15 UTC by Regina-Kapralova

2022-10-11 15:16 UTC, Ningyo requested changes

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
1.счастье принцессы похоже на ответственность принцессы. почему у вас холл это считает, да ещё и просто в консоль выводит. почему это два разных метода?
2.magic numbers

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Princess.cs
> +		public static void Skip_and_sort(IContender contender)
and в названии функции - плохой звонок. или функция имеет слишком много ответственностей, или вы неудачно выбрали название

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Princess.cs
> +		public static void Skip_and_sort(IContender contender)
зачем эта функция публичная, если её вызывает только сама принцесса

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Princess.cs
> +			if (end > 0 && Friend.Compare(contender, ex_contenders[0]) != contender)
хочется комментариев в коде, чтобы можно было просто прочитать по-человечески, что вы намереваетесь здесь делать

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Princess.cs
> +		public static void Selection()
поля - существительные, функции - глаголы. у вас функция существительное

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Princess.cs
> +			for (int i = 1; i < 30; i++)
magic number

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Princess.cs
> +				if (Friend.Compare(contender, ex_contenders[ex_contenders.Count - 2]) == contender)
если у вас версия >= C# 8, можете использовать оператор ^ вместо ex_contenders.Count - 2

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Program.cs
> +		}
скобки съехали - не совпадают по уровню со своей парой

2022-10-11 15:16 UTC, Ningyo commented on Lab1/Contender.cs
> +		public int Number { get; private set; }
оно вообще где-нибудь используется? не понимаю разницу между Mark и Number

2022-10-12 06:32 UTC, Regina-Kapralova commented on Lab1/Contender.cs
> +namespace Lab1
Исправлено на PickyBrideProblem

2022-10-12 06:33 UTC, Regina-Kapralova commented on Lab1/IContender.cs
> +
Исправлено

2022-10-12 06:34 UTC, Regina-Kapralova commented on Lab1/Contender.cs
> +		public Contender(string name, int mark, int number)
Исправлено

2022-10-12 06:36 UTC, Regina-Kapralova commented on Lab1/Friend.cs
> +			return (((Contender)contender1).Mark >= ((Contender)contender2).Mark) ? contender1 : contender2;
Подруга ведь получает претендентов для сравнения от принцессы, а принцесса априори знает только тех, кто у неё побывал.

2022-10-12 06:36 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +		private static readonly Random rnd = new Random();
Исправлено

2022-10-12 06:38 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +			StreamReader sr = new StreamReader("C:\\Users\\Регина\\OneDrive\\Рабочий стол\\Programming\\C#\\Lab1\\names.txt");
Исправлено на относительный путь

2022-10-12 06:38 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +			StreamReader sr = new StreamReader("C:\\Users\\Регина\\OneDrive\\Рабочий стол\\Programming\\C#\\Lab1\\names.txt");
Файл переименован OneHundredUniqueNames.txt

2022-10-12 06:39 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +		public static IContender Invite_contender()
Исправлено

2022-10-12 06:39 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +				if (contenders.ContainsKey(value) == true)
Исправлено

2022-10-12 06:49 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
В задании сказано "После того как принцесса сделает выбор она сможет _выйти в прихожую и понять_ кого она выбрала." К тому же принцесса сама не знает рейтинг выбранного претендента, подруга тоже, так как может только сравнить двух и то только тех, которые у принцессы уже были. Остаётся холл. 
В задании не сказано, что с результатом нужно делать что-то кроме его вывода.
Потому что выйти замуж и не выходить замуж - это разные действия. Принцесса выходит в холл и оглашает своё решение, в ответ ей сообщают, насколько это решение правильное (т.е. насколько она будет счастлива).

2022-10-12 06:50 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +		public static void Skip_and_sort(IContender contender)
Исправлено

2022-10-12 06:50 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +		public static void Skip_and_sort(IContender contender)
Исправлено

2022-10-12 06:51 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +		public static void Selection()
Исправлено

2022-10-12 06:53 UTC, Regina-Kapralova commented on Lab1/Program.cs
> +		}
Исправлено

2022-10-12 06:55 UTC, Regina-Kapralova commented on Lab1/Contender.cs
> +		public int Number { get; private set; }
Mark - это рейтинг претендента, Number - то, каким по очереди он заходит к принцессе. Действительно, не используется, убрано.

2022-10-12 13:28 UTC, Regina-Kapralova commented on Lab1/Contender.cs
> +	class Contender : IContender
Нет, у меня в Visual Studio всё ровненько, так залилось.

2022-10-12 13:34 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +	static class Hall
Холл, принцесса и подруга существуют независимо друг от друга и в единственном экземпляре, поэтому не вижу необходимости создавать объекты и оперировать ими. И в противном случае пришлось бы либо хранить холл и подругу в полях принцессы, что не логично, либо каждый раз передавать их принцессе в параметрах, что неудобно.

2022-10-12 18:39 UTC, Ningyo commented on Lab1/Contender.cs
> +	class Contender : IContender
я имела в виду не только этот файл, во всех остальных та же проблема

2022-10-12 18:49 UTC, Ningyo commented on Lab1/Friend.cs
> +			return (((Contender)contender1).Mark >= ((Contender)contender2).Mark) ? contender1 : contender2;
подруга - совершенно отдельная сущность, и то, кто и как её вызывает, никак принцессой не определяется. она должна сама следить, что ей передали корректные данные

2022-10-12 18:49 UTC, Ningyo commented on Lab1/Hall.cs
> +	static class Hall
1.если существование независимо друг от друга и в единственном экземпляре для вас аргумент для статики. тогда в каком случае она не нужна? выглядит, что практически любую систему, хоть как-то разбитую на модули, можно просто всю переписать на статике?
2.почему вы считаете "хранение" не логичным? что вы на самом деле храните в поле ссылочного типа? передавать в параметрах - да, неудобно и не нужно. потому что есть механизм внедрения зависимостей, всю прелесть которого вы поймёте в следующей лабе.

2022-10-12 18:52 UTC, Ningyo commented on Lab1/Hall.cs
> +		public static IContender Invite_contender()
один исправили, Get_married и Dont_get_married так и остались

2022-10-12 18:57 UTC, Ningyo commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
я призываю подумать логически) ваше счастье определяется прихожей? вы выходите в прихожую и спрашиваете её, насколько вы счастливы?
в конце семестра все принцессы будут соревноваться, какая в среднем более счастливая. учитывая, что в итоге у вас будут веб-службы, сомневаюсь, что счастье будет считаться по выводу в консоль. вывод в консоль на первом этапе - просто способ проверить, работает или нет

2022-10-13 03:24 UTC, Regina-Kapralova commented on Lab1/Friend.cs
> +			return (((Contender)contender1).Mark >= ((Contender)contender2).Mark) ? contender1 : contender2;
В метод Compare добавлена проверка: если претендент ещё в холле, то сравнивать нельзя.

2022-10-13 04:13 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +			for (int i = 1; i <= 100; i++)
Исправлено

2022-10-13 04:14 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +		public static IContender Invite_contender()
Исправлено

2022-10-13 04:16 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +			for (int i = 1; i < 30; i++)
Исправлено на const double partSkipedContenders = 0.3 и partSkipedContenders * Hall.countContenders

2022-10-13 04:16 UTC, Regina-Kapralova commented on Lab1/Contender.cs
> +	class Contender : IContender
Исправлено

2022-10-13 04:17 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +	static class Hall
Исправлено. Классы больше не статические и хранят экземпляры друг друга.

2022-10-13 04:40 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
У принцессы добавлена приватная переменная int levelHappinessPrincess, которая будет хранить уровень счастья принцессы и с которой далее можно будет работать, и функция ChooseContender, которая эту переменную будет определять. Методы холла объединены в один. Холл единственный знает рейтинг претендента, а значит он может либо считать счастье принцессы, либо возвращать этот рейтинг и позволять принцессе считать самой, но тогда нарушается условие задачи, ибо принцесса сможет обращаться к функции холла и получать рейтинг.

2022-10-13 07:29 UTC, Ningyo commented on Lab1/Friend.cs
> +			return (((Contender)contender1).Mark >= ((Contender)contender2).Mark) ? contender1 : contender2;
у вас получилось не "нельзя" а null. null - это ничего, неопределённость

2022-10-13 07:42 UTC, Ningyo commented on Lab1/Hall.cs
> +        private const int lowerLimitCoolnessOfContender = 50;
константы именуются в PascalCase, даже приватные

2022-10-13 07:42 UTC, Ningyo commented on Lab1/Hall.cs
> +                int value = rnd.Next(1, 101);
вот у вас есть countContenders, а это что за 101?) это опять magic

2022-10-13 07:42 UTC, Ningyo commented on Lab1/Hall.cs
> +        public const int countContenders = 100;
"посчитать претендентов" получилось глагольным

2022-10-13 07:42 UTC, Ningyo commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
смотря как реализуете. в условии сказано "После того как принцесса сделает выбор она сможет выйти в прихожую и понять кого она выбрала.". в конце принцесса должна понять, кого выбрала. как сделать так, чтобы не нарушить - нужно подумать, есть несколько вариантов. один из них, это ваше предположение "позволять принцессе обращаться к функции холла и получать рейтинг". при некоторых условиях можно. если бы холл следил, что принцесса не читерит и позволял спрашивать только раз, или только после выбора мужа или что-то в этом духе. здесь можем считать, что у холла и принцессы одинаковая продолжительность жизни, т.к. задача предполагает только один запуск

2022-10-13 07:46 UTC, Ningyo requested changes

2022-10-13 07:46 UTC, Ningyo commented on Lab1/Princess.cs
> +        private void ChooseContender(IContender contender)
функции слиплись

2022-10-24 07:30 UTC, Regina-Kapralova commented on Lab1/IContender.cs
> +        string Name { get; }
Добавлено

2022-10-24 07:33 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
Расчёт счастья принцессы перенесён в метод Принцессы. В Холле появилась переменная private bool _selectionIsFinished для контроля единственности запроса от Принцессы.

2022-10-24 07:33 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +			if (end > 0 && Friend.Compare(contender, ex_contenders[0]) != contender)
Добавлено

2022-10-24 07:33 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +        private const int lowerLimitCoolnessOfContender = 50;
Исправлено

2022-10-24 07:34 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +                int value = rnd.Next(1, 101);
Исправлено на minContendersMark и maxContendersMark соответственно

2022-10-24 07:35 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        private void ChooseContender(IContender contender)
Исправлено

2022-10-24 07:35 UTC, Regina-Kapralova commented on Lab1/Friend.cs
> +            int mark1 = ((Contender)contender1).Mark;
Добавлены проверки if (contender is Contender)

2022-10-24 07:37 UTC, Regina-Kapralova commented on Lab1/Friend.cs
> +            if (_hall.IsInHall(mark1) || _hall.IsInHall(mark2))
Заменено на поиск по имени contender.Name

2022-10-24 10:08 UTC, Regina-Kapralova commented on Lab1/Friend.cs
> +			return (((Contender)contender1).Mark >= ((Contender)contender2).Mark) ? contender1 : contender2;
return null заменено на throw new Exception

2022-10-26 12:43 UTC, Ningyo commented on Lab1/Hall.cs
> +			Console.WriteLine((contender.Mark > 50) ? contender.Mark : 0);
контроль того, что запросили GetMark только один раз - класс)

2022-10-26 12:54 UTC, Ningyo commented on Lab1/Hall.cs
> +        public const int countContenders = 100;
amount тоже может быть глаголом) я про порядок слов глагол + существительное. можно просто of добавить, можно порядок поменять

2022-10-26 12:58 UTC, Ningyo commented on Lab1/Friend.cs
> +            int mark1 = ((Contender)contender1).Mark;
с проверкой is получается, что вы обманываете пользователя функции её контрактом. вы заявляете, что принимаете IContender как аргумент, а по факту ожидаете совершенно другого. если представить, что у IContender есть несколько реализаций, то сколько бы их ни было, функция подруги, которая заявляет, что может сравнить **любых двух IContender**, на самом деле будет работать только для одного конкретного вида претендентов. это неправильно.

2022-10-26 12:59 UTC, Ningyo commented on Lab1/Friend.cs
> +            int mark1 = ((Contender)contender1).Mark;
это касается так же других подобных функций, где вы внутри приводите IContender к Contender явным образом, обманывая в контракте

2022-10-26 13:00 UTC, Ningyo commented on Lab1/Hall.cs
> +            return (_contenders.ContainsValue(name)) ? true : false;
значение какого типа возвращает функция ContainsValue и обязательно ли после этого проверять "?:" ?

2022-11-01 07:39 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +        public const int countContenders = 100;
Исправлено на AmountOfContenders

2022-11-01 07:41 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +            return (_contenders.ContainsValue(name)) ? true : false;
Ой, действительно :) исправлено

2022-11-01 08:57 UTC, Ningyo commented on Lab1/Hall.cs
> +        public bool Compare(string name1, string name2)
по условию, сравнивать должна подруга, а не холл) вы можете сделать метод в холле, который будет возвращать или целиком претендента, или аналог GetMark для подруги. но тогда нужно два интерфейса для холла, чтобы принцесса физически просто не могла вызвать методы для подруги, имея на руках только свой холл для принцессы

2022-11-02 07:24 UTC, Regina-Kapralova commented on Lab1/Hall.cs
> +        public bool Compare(string name1, string name2)
Добавлены интерфейсы IHallForPrincess и IHallForFriend, метод GetMarkForFriend

2022-11-06 06:09 UTC, merged