change
Regina-Kapralova/C_Sharp pull request #2
Opened 2022-11-21 13:09 UTC by Regina-Kapralova

2022-11-22 08:43 UTC, Ningyo requested changes

2022-11-22 08:43 UTC, Ningyo commented on Lab1/ContenderGenerator.cs
> +            StreamReader sr = new StreamReader("OneHundredUniqueNames.txt");
сложная логика в конструкторе - не очень хорошо. потенциально асинхронная логика в конструкторе - ещё хуже. в идеале конструктор просто подготавливает класс к дальнейшему использованию, занимается простой инициализацией и т.п.

2022-11-22 08:43 UTC, Ningyo commented on Lab1/Princess.cs
> +                _levelHappinessPrincess = 0;
magic здесь и ниже

2022-11-22 08:43 UTC, Ningyo commented on Lab1/Princess.cs
> +        /*private void ChooseContender(IContender contender)
если не используется - надо удалять

2022-11-22 08:43 UTC, Ningyo commented on Lab1/Program.cs
> +                    services.AddScoped<IHallForPrincess>(sp => hall);
sp.GetRequiredService

2022-11-22 08:43 UTC, Ningyo commented on Lab1/Program.cs
> +                    ContenderGenerator contenderGenerator = new ContenderGenerator();
можно сразу зарегистрировать, не создавая вручную. здесь и для холла

2022-11-22 08:43 UTC, Ningyo commented on Lab1/Program.cs
> +
лишняя строка

2022-12-06 03:52 UTC, Regina-Kapralova commented on Lab1/Program.cs
> +
Исправлено

2022-12-06 03:53 UTC, Regina-Kapralova commented on Lab1/Program.cs
> +                    ContenderGenerator contenderGenerator = new ContenderGenerator();
Исправлено

2022-12-06 03:53 UTC, Regina-Kapralova commented on Lab1/Program.cs
> +                    services.AddScoped<IHallForPrincess>(sp => hall);
Исправлено

2022-12-06 03:53 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        /*private void ChooseContender(IContender contender)
Удалено

2022-12-06 03:54 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +                _levelHappinessPrincess = 0;
Добавлены константы с "говорящими именами"

2022-12-06 03:55 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +            StreamReader sr = new StreamReader("OneHundredUniqueNames.txt");
Сложная логика вынесена в функции Init()

2022-12-06 07:51 UTC, Ningyo requested changes

2022-12-06 07:51 UTC, Ningyo commented on Lab1/Princess.cs
> +            const int LevelHappinessPrincessMarriedАifthContender = 100;
Аifth

2022-12-06 07:57 UTC, Ningyo approved these changes

2022-12-06 07:57 UTC, merged