Lab3
Regina-Kapralova/C_Sharp pull request #3
Opened 2022-12-24 10:11 UTC by Regina-Kapralova

2022-12-25 08:10 UTC, Ningyo requested changes

2022-12-25 08:10 UTC, Ningyo commented on Tests/ContenderGeneratorTest.cs
> +            private int AmountOfContenders;
_

2022-12-25 08:10 UTC, Ningyo commented on Tests/ContenderGeneratorTest.cs
> +        public class ContenderGeneratorTest
как поведёт себя генератор, если попросить его сгенерить <1 и >100 претендентов?

2022-12-25 08:10 UTC, Ningyo commented on Tests/ContenderGeneratorTest.cs
> +            private int AmountOfContenders;
здесь и в подобных местах

2022-12-25 08:10 UTC, Ningyo commented on Tests/FriendTest.cs
> +        }
функции слиплись, не хватает пустой строки

2022-12-25 08:10 UTC, Ningyo commented on Tests/FriendTest.cs
> +            IContender firstContender = hall.InviteContender();
можно просто var, и так понятно, что это претендент

2022-12-25 08:10 UTC, Ningyo commented on Tests/FriendTest.cs
> +            IContender firstContender = hall.InviteContender();
лучше по смыслу назвать, не просто первый-второй-третий, а качественно, как-нибудь худший-средний-лучший. иначе не очень понятно читается, почему второй лучше первого

2022-12-25 08:10 UTC, Ningyo commented on Tests/HallTest.cs
> +        List<Contender> CreateContenderList()
функции слиплись

2022-12-25 08:10 UTC, Ningyo commented on Tests/HallTest.cs
> +            hall.InviteContender().Should().Be(firstContender);
лучше не be, а BeEquivalentTo. иначе вы сравниваете только по ссылке, и если у вас не перегружен Equals, то  hall.InviteContender().Should().Be(new Contender("Артём", 1)); скажет вам false

2022-12-25 08:10 UTC, Ningyo commented on Tests/HallTest.cs
> +    class HallTest
у вас в холле только метод InviteContender есть, или можно ещё что-нибудь проверить?

2022-12-25 08:10 UTC, Ningyo commented on Tests/PrincessTest.cs
> +            Mock<IContenderGenerator> contenderGenerator = new Mock<IContenderGenerator>();
инициализацию можно вынести в отдельный метод? у вас код из теста в тест практически повторяется, хотя разница только в списке претендентов

2022-12-25 08:10 UTC, Ningyo commented on Tests/PrincessTest.cs
> +        public void PrincessMarriedFirstContender()
первый - это просто по порядку первый? или с самым высоким баллом? не очень понятно

2022-12-25 08:10 UTC, Ningyo commented on Tests/PrincessTest.cs
> +        public void ThrowExceptionTest()
не очень из названия понятно, почему ошибка произойти должна

2022-12-25 15:36 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +        public void Init(int AmountOfContenders)
Исправлено

2022-12-25 15:36 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +            while (_contenders.Count > 0) {
Исправлено

2022-12-25 15:37 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +                while (true)
Не справился.

2022-12-25 15:38 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +            return _contendersForHall;
Список претендентов List<Contender>

2022-12-25 15:38 UTC, Regina-Kapralova commented on Lab1/IContenderGenerator.cs
> +        }
Исправлено

2022-12-25 15:38 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        private int AmountOfExContenders;
Исправлено

2022-12-25 15:40 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        public int GetLevelHappiness()
Выбор претендента - приватный метод принцессы, который ничего не возвращает, а устанавливает значение приватной переменной принцессы _levelHappinessPrincess. Чтобы кто-то мог поинтересоваться счастьем принцессы, нужен отдельный метод.

2022-12-25 15:40 UTC, Regina-Kapralova commented on Tests/ContenderGeneratorTest.cs
> +            private int AmountOfContenders;
Исправлено

2022-12-25 15:41 UTC, Regina-Kapralova commented on Tests/ContenderGeneratorTest.cs
> +        public class ContenderGeneratorTest
Добавлена ошибка при попытке создать такой список и тест на эту ошибку.

2022-12-25 15:41 UTC, Regina-Kapralova commented on Tests/FriendTest.cs
> +        }
Исправлено

2022-12-25 15:41 UTC, Regina-Kapralova commented on Tests/FriendTest.cs
> +            IContender firstContender = hall.InviteContender();
Исправлено

2022-12-25 15:42 UTC, Regina-Kapralova commented on Tests/FriendTest.cs
> +            IContender firstContender = hall.InviteContender();
Исправлено

2022-12-25 15:42 UTC, Regina-Kapralova commented on Tests/HallTest.cs
> +        List<Contender> CreateContenderList()
Исправлено

2022-12-25 15:42 UTC, Regina-Kapralova commented on Tests/HallTest.cs
> +            hall.InviteContender().Should().Be(firstContender);
Исправлено

2022-12-25 15:42 UTC, Regina-Kapralova commented on Tests/HallTest.cs
> +    class HallTest
Добавлены тесты для трёх оставшихся методов холла.

2022-12-25 15:43 UTC, Regina-Kapralova commented on Tests/PrincessTest.cs
> +            Mock<IContenderGenerator> contenderGenerator = new Mock<IContenderGenerator>();
Исправлено

2022-12-25 15:43 UTC, Regina-Kapralova commented on Tests/PrincessTest.cs
> +        public void PrincessMarriedFirstContender()
Исправлено

2022-12-25 15:43 UTC, Regina-Kapralova commented on Tests/PrincessTest.cs
> +        public void ThrowExceptionTest()
Исправлено

2022-12-26 13:53 UTC, Ningyo commented on Lab1/ContenderGenerator.cs
> +                while (true)
выглядит подозрительно. тем более бесконечный while - штука потенциально опасная

2022-12-26 13:56 UTC, Ningyo commented on Lab1/ContenderGenerator.cs
> +            return _contendersForHall;
и если в этот список извне кто-нибудь что-нибудь добавит, например, изменится ли ContenderGenerator. _contendersForHall?

2022-12-26 13:57 UTC, Ningyo commented on Lab1/Princess.cs
> +        private int AmountOfExContenders;
ну почти. с _ и маленькой буквы. у вас же уже есть примеры в вашем же проекте

2022-12-26 13:58 UTC, Ningyo commented on Lab1/Princess.cs
> +        public int GetLevelHappiness()
а что мешает сразу вернуть счастье? у вас бывают случаи, когда эти два метода должны использоваться не вместе?

2022-12-26 14:06 UTC, Ningyo requested changes

2022-12-26 14:06 UTC, Ningyo commented on Tests/ContenderGeneratorTest.cs
> +            newContenderGenerator.Invoking(f => f.Init(-5))
1.почему -5? это не граничное значение. обычно выбирают граничные. если 0 - ок, то нужно проверить на -1, полагая, что дальше за -1 поведение будет аналогичным. так остаются вопросы, а что на промежутке от 0 до -5 происходит? то же со 150
2.у вас два теста в одном фактически. это два разных кейса. см. [TestCase] в NUnit или аналогичное в том фреймфорке, что используете
3.название теста Test - не говорящее)

2022-12-26 14:06 UTC, Ningyo commented on Tests/HallTest.cs
> +            hall.IsInHall("Артём").Should().Be(true);
можно использовать сразу BeTrue() и BeFalse()

2022-12-26 15:18 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        public int GetLevelHappiness()
Потому что выбрать претендента может только принцесса, и ей в принципе не нужно, чтобы метод что-то возвращал. Метод с возвратом нужен другими классами, если они хотят узнать счастье принцессы, эта функция используется в тестах.

2022-12-26 15:26 UTC, Regina-Kapralova commented on Tests/HallTest.cs
> +            hall.IsInHall("Артём").Should().Be(true);
Исправлено

2022-12-26 15:26 UTC, Regina-Kapralova commented on Tests/ContenderGeneratorTest.cs
> +            newContenderGenerator.Invoking(f => f.Init(-5))
Исправлено

2022-12-26 15:26 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        private int AmountOfExContenders;
Исправлено

2022-12-26 15:26 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +            return _contendersForHall;
Он же приватный, как туда извне что-то добавят? Перенесла лист в метод, теперь точно никто не доберётся.

2022-12-27 08:36 UTC, Ningyo commented on Lab1/Princess.cs
> +        private int AmountOfExContenders;
PrincessTest

2022-12-27 08:40 UTC, Ningyo commented on Tests/ContenderGeneratorTest.cs
> +            newContenderGenerator.Invoking(f => f.Init(-5))
TestCase

2022-12-27 09:14 UTC, Regina-Kapralova commented on Lab1/ContenderGenerator.cs
> +                while (true)
Исправила

2022-12-27 09:14 UTC, Regina-Kapralova commented on Tests/ContenderGeneratorTest.cs
> +            newContenderGenerator.Invoking(f => f.Init(-5))
Исправила

2022-12-27 09:14 UTC, Regina-Kapralova commented on Lab1/Princess.cs
> +        private int AmountOfExContenders;
Исправила

2022-12-27 10:58 UTC, merged